Repository kokuwaio/keycloak, pull requests merged in 2022-08, with the labels that each got.

#24 Add tag for specific version, fix #23
  .github/dependabot.yml
  .github/workflows/build.yaml
  README.md
Labels: enhancement

#25 Replace spotify docker plugin with fabric8, rel #9
  .github/workflows/build.yaml
  pom.xml
  src/main/docker/Dockerfile
  src/test/k3s/keycloak/job.yaml
  src/test/k3s/keycloak/statefulset.yaml
Labels: dependencies

#27 Replace fabric8 with exec-maven-plugin, rel #9
  pom.xml
Labels: dependencies

#26 Add arch arm64, fix #9
  .github/workflows/build.yaml
Labels: enhancement

#29 add docker to dependabot
  .github/dependabot.yml
Labels: dependencies

#34 Change base image from `distroless` to `eclipse-temurin`, fix #33
  README.md
  src/main/docker/Dockerfile
Labels: bug, dependencies
